### ISSUE TITLE
compareArrays() function never finds a match

### ISSUE THREAD

**Issue by Sporran** [saebekassebil/piu#2]
The compareArrays() function in the file triads.js currently fails to fire for matching arrays (see my test environment details further below).

I'm no array expert, but found that the function fires correctly if a string-based comparison is made. Maybe you have a better approach:

```
if (first[i].toString() !== second[i].toString()) {..}
```

Incidentally, omission of curly brackets is (apparently) dangerous practice. Just sayin' like.. Otherwise, altogether a nice piece of code: and does something vexflow's music.js doesn't.. :-)

Environment:
MacBook Pro  (Mac OS X Lion 10.7.5)
Node v0.10.29

**Comment by saebekassebil** [comment]
It works as intended here? And no, leaving out curly brackets is not a dangerous practice in my opinion. It makes for lighter and thus easier to read code.

Cool that you find piu helpful! I'd very much like to hear what you're using it for - and if you're still experiencing problems please open another issue.

Since the `compareArray` function is never exported I don't really understand how you ran into this problem?

**Comment by Sporran** [comment]
compareArray() is called from within it's own module (triads.js). In it's current form, though addition of console logging reveals matches, in my environment these are never trapped by the code (always returns false). Could try on a virtual box with Ubuntu, I guess.

As to uses, should piu & teoria prove fast enough, there would seem to be several - such as chord diagram generation or in a circle of fifths.

**Comment by saebekassebil** [comment]
It makes no sense trying to alter the environment - the code should execute the same.

Could you share the code that you've run to find this issue?

**Comment by Sporran** [comment]
Basically, running  the piu module tests using vows:

```
andrews-macbook-pro:piu$ vows test/* --verbose
```

I get:
    vows runner finish
    piu.infer() with enharmonic inferring enabled 
      ✗ d, f, ab, cb is enharmonic equivalent to 4 dim7 chords 
      Error: Invalid parameters 
      at Object.teoria.interval (/Users/xxxxx/node_modules/teoria/dist/teoria.js:311:11) 
      at Object.TeoriaInterval.simple (/Users/xxxxx/node_modules/teoria/dist/teoria.js:629:21) 
      at /Users/xxxxx/piu/lib/triads.js:64:80 
      at Array.forEach (native) 
      at module.exports.exports (/Users/xxxxx/piu/lib/triads.js:59:4) 
      at infer (/Users/xxxxx/piu/lib/infer.js:42:12) 
      at /Users/xxxxx/piu/lib/infer.js:18:14 
      at Array.map (native) 
      at Object.infer (/Users/xxxxx/piu/lib/infer.js:17:45) 
      at names (/Users/xxxxx/piu/test/names.js:18:14) 
      at Object.vows.describe.addBatch.piu.infer() with enharmonic inferring enabled.d, f, ab, cb is enharmonic equivalent to 4 dim7 chords (/Users/xxxxx/piu/test/names.js:144:24) 
  ✗ Errored » 29 honored ∙ 1 errored (1.321s) 
  andrews-macbook-pro:piu xxxxx$

Then, testing with the following (own) file  in the piu directory, I get no chord output (result lengths all 0).

```
var teoria  = require('teoria');
var piu     = require('./index');

var result1 = piu.infer( ['c', 'e', 'g'].map(teoria.note) ).map( piu.name );
console.log("typeOf(result1)=" + typeof(result1) + " result1.length=" + result1.length);
console.log("piu.infer( ['c', 'e', 'g'].map(teoria.note) ).map( piu.name )=" + result1);

var result2 = piu.infer( ['d', 'f', 'a', 'c'].map(teoria.note) ).map( piu.name );
console.log("typeOf(result2)=" + typeof(result2) + " result2.length=" + result2.length);
console.log("piu.infer( ['d', 'f', 'a', 'c'].map(teoria.note) ).map( piu.name )=" + result2);

// Infer the chords (enharmonically) constituted by the notes B, D, F and Ab
var result3 = piu.infer( ['b', 'd', 'f', 'ab'].map(teoria.note) ).map( piu.name );
console.log("typeOf(result3)=" + typeof(result3) + " result3.length=" + result3.length);
console.log("piu.infer( ['b', 'd', 'f', 'ab'].map(teoria.note) ).map( piu.name )=" + result3);
```

Using console logging, I was able to track the problem down to the function compareArray().

I'm a complete node begginer and can't remember how I installed piu and teoria. Could have been using any of git, node or (directly) npm. Maybe I should just clean and reinstall everything using npm.

**Comment by saebekassebil** [comment]
Yes, you should try reinstalling with npm. I noticed an error that occurred when using an older version of piu. Make sure you’ve piu~1.0.0 installed.

// Jakob

Den 09/07/2014 kl. 12.15 skrev Sporran notifications@github.com:
