### ISSUE TITLE
conflict between function name and ES6 built-in function property

### ISSUE THREAD

**Issue by Sporran** [saebekassebil/piu#3]
It is apparently considered good practice to avoid using the name of JavaScript built-in objects, properties, and methods.

The function name() is defined in the piu file name.js.

Under the JavaScript Harmony (EMCAScript 6) proposal, "name" also becomes a property of a function. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

I could imagine this leading to performance or other issues. As a precaution, best perhaps renamed..

**Comment by saebekassebil** [comment]
Since we do not attach the `name()` function to a `Function` but an `Object` (`module.exports`), there should be no problem in doing so.
