### ISSUE TITLE
Fed the same input notes, calls to piu.name() exit, but to piu.infer() continue

### ISSUE THREAD

**Issue by Sporran** [saebekassebil/piu#4]
Piu is exiting with error while trying to process legitimate component chord notes scraped from a Mozart piece: 
http://imslp.org/wiki/String_Quartet_No.17_in_B-flat_major,_K.458_(Mozart,_Wolfgang_Amadeus)
(Also available in musicxml or finale format at http://www.gutenberg.org/ebooks/4951).

Typically, a call such as:

`current_chord = piu.name( piu.infer(notes_array.map(teoria.note))[0] );`

is (for the notes shown immediately below) rewarded with the error:

`01:17:47:542 chordnames.js: for notes_array = F,A,Bb`

(More problematic note examples can be found at the foot).

`/Users/xxxxxxx/node_modules/piu/lib/name.js:36
  var root = chord.root, type = chord.type, exts = chord.exts, rest;
                  ^
TypeError: Cannot read property 'root' of undefined
    at Object.module.exports.exports [as name] (/Users/xxxxxxx/node_modules/piu/lib/name.js:36:19)
    at Object.<anonymous> (/Users/xxxxxxx/node_modules/piu/test/chord_names.js:650:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
$`

**BACKGROUND**

My test is a little unconventional in that (enharmonically) duplicate notes are removed, and that the note order is more or less irrelevant (they are later 12TET-ordered using `midi_num = midi_num % 12;`).

**INCONSISTENCY**

While clear that Piu will not find a chord for every set of notes, it seems inconsistent to return (for the same input) an empty object for the `piu.infer()` case (which is fine), but exit with error for the `piu.name()` variant. It would be helpful if both were to behave similarly.

To sustain the shape of Cof5ths chords in an animation, each note is sampled repeatedly until it's duration expires. This approach tends to highlight problematic locations.

**WORKAROUND**

The only workaround I've found which allows use of `piu.name( piu.infer(notes_array.map(teoria.note))[0] );` is to make a 'screening' call to the following first:

`current_chord_as_object = piu.infer( notes_array.map( teoria.note ) ).map( piu.name );`

Where the resulting `current_chord_as_object.length === 0`, the matching `piu.name()` call can simply be overstepped, allowing processing of the next chord rather than a bumpy exit.

![screen shot 2014-08-01 at 14 36 31](https://cloud.githubusercontent.com/assets/651083/3785074/33f9a97e-19bf-11e4-8976-643df82eb44f.png)
Measure 4, divs: '29': **["D", "F", "C"]**    and    '34': **["Bb", "Eb", "C"]**

![screen shot 2014-08-01 at 14 52 14](https://cloud.githubusercontent.com/assets/651083/3785059/f8b6e14c-19be-11e4-8a4f-cad31ea82a4e.png)
Measure 8, div:  '84': **["A", "C", "Eb", "F"]**

![screen shot 2014-08-01 at 14 58 38](https://cloud.githubusercontent.com/assets/651083/3785039/d38f07f0-19be-11e4-815a-5e3def12ad89.png)
Measure 9, div:  '89': **["A", "D", "Bb"]**

![screen shot 2014-08-01 at 15 03 29](https://cloud.githubusercontent.com/assets/651083/3785029/b6c43596-19be-11e4-971a-6dabb926aa28.png)
Measure 10, div:  '104': **["Eb", "C", "Bb"]**

![screen shot 2014-08-01 at 15 35 06](https://cloud.githubusercontent.com/assets/651083/3785019/9c2f5e40-19be-11e4-92e6-47bf67d09718.png)
Measure 11, div:  '118': **["F", "A", "Bb"]**

![screen shot 2014-08-01 at 15 38 48](https://cloud.githubusercontent.com/assets/651083/3785005/79f4d260-19be-11e4-93c5-1f1fd4c6c3ad.png)
Measure 12, divs '122': **["Eb", "C", "F"]**    and    '127': **["D", "C", "F"]**

![screen shot 2014-08-01 at 15 43 09](https://cloud.githubusercontent.com/assets/651083/3784981/3ea45f82-19be-11e4-8163-b1ee44f9c3f2.png)
Measure 13, div '135': **["Eb", "D", "Bb"]**

![screen shot 2014-08-01 at 16 00 19](https://cloud.githubusercontent.com/assets/651083/3784887/943cba8a-19bd-11e4-91f3-cc93237bf78c.png)
Measure 16, divs  '170': **["Eb", "A", "F"]**    and    '171': ["D", "Eb", "A", "F"]    and    '172': ["C", "Eb", "A", "F"]    and    '173': ["Bb", "Eb", "A", "F"]    and    '176': ["C", "Eb", "F"]    and    '180': ["G", "Eb", "F"]    and    '181': **["A", "Eb", "F"]**

![screen shot 2014-08-01 at 16 09 35](https://cloud.githubusercontent.com/assets/651083/3784872/78024628-19bd-11e4-99e5-0ca70128cd0f.png)
Measure 17, div  '189': **["D", "Eb", "F"]**
![screen shot 2014-08-01 at 16 12 42](https://cloud.githubusercontent.com/assets/651083/3784831/10ab4150-19bd-11e4-8228-1ae7869e828a.png)
'206': **["D", "F", "Bb"]**

**Comment by saebekassebil** [comment]
Hey Sporran - This looks intriguing and I'll have to look at it in greater
detail, but these following weeks I'll have very little time for
programming. I'll return as soon as possible!

2014-08-02 0:15 GMT+02:00 Sporran notifications@github.com:

**Comment by saebekassebil** [comment]
Hi Sporran!

Should be fixed by e3aca0c4f5e0556a5e36e233801b8e8e34aa89db

Can I hear more about your project? It seems really interesting!
